# @package _global_
module:
  _target_: emg2qwerty.lightning.GRUCTCModule
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  hidden_size: 128  # Hidden size for GRU layers
  num_layers: 4     # Number of GRU layers
  bidirectional: True  # Use bidirectional GRU
  dropout: 0.3  # Dropout for regularization

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
