# @package _global_
module:
  _target_: emg2qwerty.lightning.GRUCTCModule
  in_features: 128  # Adjust based on the output size from previous layers (e.g., MLP or Conv2D layers)
  gru_hidden_size: 128  # Hidden size of the GRU layer
  num_gru_layers: 2  # Number of GRU layers
  dropout: 0.3  # Dropout rate for regularization
  output_classes: 10  # Adjust this based on the number of output classes (e.g., number of characters)

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
