# @package _global_
module:
  _target_: emg2qwerty.lightning.HybridCTCModule
  in_features: 528  
  mlp_features: [384] 
  block_channels: [24, 24, 24, 24, 24, 24] 
  kernel_width: 32  
  lstm_hidden_size: 120 
  gru_hidden_size: 128 
  num_lstm_layers: 2  
  num_gru_layers: 2  
  num_transformer_layers: 2  
  num_heads: 8  

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context

