# @package _global_
module:
  _target_: emg2qwerty.lightning.HybridCTCModule
  in_features: 528  # Adjust based on your input spectrogram size
  mlp_features: [384]  # Feature extraction layers
  block_channels: [24, 24, 24, 24]  # Channels for TDSConv blocks
  kernel_width: 32  # Kernel size for TDSConv
  lstm_hidden_size: 120  # Hidden size for BiLSTM
  gru_hidden_size: 128  # Hidden size for BiGRU
  num_lstm_layers: 2  # Number of LSTM layers
  num_gru_layers: 2  # Number of GRU layers
  num_transformer_layers: 2  # Number of Transformer layers
  num_heads: 8  # Transformer multi-head attention heads

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context

