# @package _global_
module:
  _target_: emg2qwerty.lightning.LSTMEncoderCTCModule
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [384]
  hidden_sizes: [128, 128, 128, 128]  # Hidden state sizes for each LSTM layer
  num_layers: 4  # Matching the number of CNN layers in MultiLayerCNNCTCModule
  bidirectional: True  # Use bidirectional LSTMs
  dropout: 0.2  # Dropout for LSTM layers

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
