# @package _global_
module:
  _target_: emg2qwerty.lightning.SimpleCNNCTCModule
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [384]
  block_channels: [32, 64, 128]  # Channels used in CNN layers
  kernel_width: 3  # Standard 3x3 kernel for CNN

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
  batch_size: 32
  