# @package _global_
module:
  _target_: emg2qwerty.lightning.TransformerCTCModule
  in_features: 528  
  num_layers: 4
  num_heads: 8
  feedforward_dim: 256
  dropout: 0.1

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
