# @package _global_
module:
  _target_: emg2qwerty.lightning.TransformerEncoderCTCModule
  in_features: 528  
  mlp_features: [384]
  block_channels: [24, 24, 24, 24] 
  num_heads: 8 
  feedforward_dim: 512  
  num_layers: 4  
  dropout: 0.1

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context

