# @package _global_
module:
  _target_: emg2qwerty.lightning.TransformerCTCModule
  in_features: 528  # Same as TDSLSTM
  mlp_features: [384]  # Same as TDSLSTM
  num_layers: 4  # Transformer depth
  num_heads: 8  # Multi-head attention heads
  feedforward_dim: 512  # Feedforward layer size inside Transformer blocks
  dropout: 0.1  # Dropout rate

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
